### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by fjinkis** [Kelsus/api-spot-package#10]
# Expected Behavior

Since there isn't any requirement section in the docs, it should work with any Node version.

# Current Behavior

For version lower than 14.x the operators `?` (optional chaining) and `??` (nullish coalescing) don't exist

# Proposed Solution

You can slightly modify those operations to something less fancy but backwards compatible or add it as a requirement in the package documentation

# Other information

Some deploy logs:
```shell
/home/circleci/project/node_modules/@kelsus/api-spot-package/index.js:81
    if (!match || !(match.groups?.owner && match.groups?.name)) return null;
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/@kbs/kelsus-deploy/src/extensions/report-spot.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

Exited with code exit status 1
```

**Comment by cesaraugustogarcia** [comment]
Hi @fjinkis thanks for the details on the issue.

I have just released a new versión that does not uses operators ? (optional chaining) and ?? (nullish coalescing), hoping that now it is compatible with older node versions. 

I have tried with Node version 12, since this operators were introduced in Node.js `v14.0.0`  (V8 8.1).

It worked on my local
```
Cesars-MacBook-Pro:api-spot-node-version-test cesaraugustogarcia$ npx @kelsus/api-spot-package
npx: installed 1 in 3.998s
Unexpected token '.'
Cesars-MacBook-Pro:api-spot-node-version-test cesaraugustogarcia$ node -v
v12.22.7
Cesars-MacBook-Pro:api-spot-node-version-test cesaraugustogarcia$ npx @kelsus/api-spot-package
npx: installed 1 in 6.347s
***************************************************************************
Notifying deploy spot API
***************************************************************************
SPOT_API_KEY Environment variable  not found.
Cesars-MacBook-Pro:api-spot-node-version-test cesaraugustogarcia$ node -v
v12.22.7
```

Please let me know if you are able to use it now.

**Comment by cesaraugustogarcia** [comment]
Following the recommendation we decided to remove the new fancy operators introduced for Node versions superior than 14, making it compatible with older versions.
Isssue has been confirmed to be solved by @fjinkis , thanks!
