### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by fjinkis** [Kelsus/api-spot-package#8]
# Expected Behavior

Kelsus Spot should take project's version

# Current Behavior

Kelsus Spot gets the `api-kelsus-spot` package's version

# Proposed Solution

Maybe you can use some variable like `process.cwd()` or a library as `find-package-json`

# Other information

Some deploy logs:
```shell
***************************************************************************
Notifying deploy spot API
***************************************************************************
-- Found a CI env variable --
Checking for CI variables: CIRCLE_PROJECT_REPONAME,CIRCLE_BRANCH,CIRCLE_BUILD_NUM
Found variable: CIRCLE_PROJECT_REPONAME
Found variable: CIRCLE_BRANCH
Found variable: CIRCLE_BUILD_NUM
Got 'version' 1.3.18 from package.json. (It might be replaced with an Env variable)
...
```

package.json
```json
{
  "name": "***************",
  "version": "0.0.70",
  ...
}
```

**Comment by cesaraugustogarcia** [comment]
Issue has been fixed, validated with several projects: `splunk-show-api`, `deploy-spot-webapp` and `api-spot-package`
